### ISSUE TITLE
v2.3.6-srh-extra -> v2.4.0 official

### ISSUE THREAD

**Issue by CyberiumShadow** [srh/rethinkdb#1]
Hey, Not sure if this belongs here but would there be any issues in transitioning from v2.3.6-srh-extra to the just released v2.4.0 official version?

**Comment by srh** [comment]
Hmm.

Since you're using it, could you tell me -- are you experiencing any problems with memory leaks when using it?

So, generally speaking, it will work -- I haven't tested this act of `v2.3.6-srh-extra => v2.4.0` since a couple of years ago though -- it was designed out of the box to allow drop-in downgrading, *and* to support both this upgrade path and the `v2.3.6-srh-extra => v2.4.0-srh-extra` upgrade path.  If you do run it, I *think* you'll lose the user configuration of the flush interval, and well as the actual flushing behavior that was implemented, because v2.4.0 does not support that.

I had backported the srh-extra changes to both the v2.3.x and v2.4.x branches, so making a v2.4.0-srh-extra release would be in order.

**Comment by CyberiumShadow** [comment]
As far as I can tell, (my usecase for rethinkdb is relatively small) there haven't been any indications of a memory leak

**Comment by srh** [comment]
If you're using the flush interval feature, I think you should wait for the v2.4.0-srh-extra release, and please send me an email if I don't make it before Monday.

**Comment by srh** [comment]
You didn't send me an email :-)

v2.4.0-srh-extra is released.

https://github.com/srh/rethinkdb/releases/tag/v2.4.0-srh-extra
