### ISSUE TITLE
Build for armhf?

### ISSUE THREAD

**Issue by mafineeek** [srh/rethinkdb#4]
Hey, is it possible to upload build for armhf architecture?

**Comment by srh** [comment]
It is possible.

If you have a bash script or command line invocation that will cross-compile the build from an x86-64 or arm64 linux system, without me having to think about it, I would be happy to run it for free and upload the build.

Otherwise, I would have to spend a small amount of time figuring it out and sanity testing the build output, and supporting 32-bit ARM systems is not a priority for me.  Email me for my billing rates (heavily discounted for something like this) if it's important.
